### PR TITLE
Rollet oso patch 3

### PR DESCRIPTION
**Pull request by RolletOso**

### CODE REVIEW

**Comment by ausbitbank** [comment]
Thankyou very much for your contribution, I'll probably tweak the description in About Us before the next version goes live, but it's still better then nothing. The privacy policy is a little redundant too since Steemviz doesn't collect or store any user data at all, but it's still appreciated and will be included in the next released version. Cheers!

**Comment by RolletOso** [comment]
Greetings Ausbitbank.

You know about Utopian. I hope you know that you can make task requests for
other people to contribute to helping out with the frontend of steemviz to
help mobile users and other users fully benefit from it. Like i said
before, i love the idea of SteemViz and i will love to see it attain some
unimaginable heights.

Just think about it and i will explain how you can create task requests for
other programmers to help with some new features.

Thanks

**Comment by RolletOso** [comment]
Hello Greetings

**Comment by ausbitbank** [comment]
Yes Hi, I'm aware of utopian but I'm not looking for any contributors right now. Like I said to you earlier I already have a complete revamp in the works.

**Pull request merged**
